name: 🐳 Build Multi-Platform Docker Image and Run Scout 🕵️‍♀️

on:
  push:
    tags:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

permissions:
  security-events: write    # Required for uploading SARIF results
  actions: read             # Required to get Action run status
  pull-requests: write      # Required to comment on PRs

# Define environment variables at the workflow level
env:
  DOCKER_REGISTRY: docker.io
  DOCKER_NAMESPACE: philippecharriere494
  DOCKER_IMAGE_NAME: gha-scout-hello-demo
  SARIF_FILE: sarif.output.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: 🐙 Checkout code
        uses: actions/checkout@v4

      # Set up QEMU for multi-architecture builds
      - name: 🏗️ Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      # Set up Docker Buildx
      - name: 🔧 Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: 🐳 Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # Build and push the Docker image for tag events
      - name: 📦 Build and push Docker image on push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}
          sbom: true
          provenance: true

      # Build Docker image for PR events (not pushed)
      - name: 🎁 Build Docker image on PR
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          load: false  # Can't use load with multi-platform builds
          push: false
          tags: ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:pr-${{ github.event.number }}
          sbom: false
          provenance: false
          
      # Build single platform image for scanning in PR
      - name: 🎁 Build amd64 image for PR scanning
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          load: true  # Load into local Docker daemon for scanning
          push: false
          tags: ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:pr-${{ github.event.number }}-scan
          sbom: false
          provenance: false

      # Set image name variable based on event type
      - name: 🏷️ Set Docker image name variable
        id: image-name
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "FULL_IMAGE_NAME=${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}" >> $GITHUB_ENV
            echo "FULL_IMAGE_NAME=${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}"
          else
            # For PR scans, use the single platform image
            echo "FULL_IMAGE_NAME=${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:pr-${{ github.event.number }}-scan" >> $GITHUB_ENV
            echo "FULL_IMAGE_NAME=${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:pr-${{ github.event.number }}-scan"
          fi

      - name: 🔍🤔 Run Scout scan on PR
        if: github.event_name == 'pull_request'
        uses: docker/scout-action@v1
        with:
          command: quickview
          image: ${{ env.FULL_IMAGE_NAME }}
          
      - name: 👀🤔 Compare to deployed image
        id: docker-scout-compare
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: docker/scout-action@main
        with:
          command: compare
          image: ${{ env.FULL_IMAGE_NAME }}
          only-severities: critical,high
          to-env: prod
          exit-code: true       
          summary: true

      - name: 🚨 Analyze PR for CVEs
        if: github.event_name == 'pull_request'
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ env.FULL_IMAGE_NAME }}
          only-severities: critical,high
          exit-code: true
          sarif-file: ${{ env.SARIF_FILE }}

      - name: 💬 Comment PR with Scout results
        if: github.event_name == 'pull_request'
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ env.FULL_IMAGE_NAME }}
          only-severities: critical,high
          summary: true
          write-comment: true

      - name: 🔍 Run Scout scan on tag
        if: github.event_name == 'push'
        uses: docker/scout-action@v1
        with:
          command: quickview
          image: ${{ env.FULL_IMAGE_NAME }}

      - name: 🐞 Analyze for critical and high CVEs
        id: docker-scout-cves
        if: github.event_name == 'push'
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ env.FULL_IMAGE_NAME }}
          sarif-file: ${{ env.SARIF_FILE }}
          summary: true

      # Upload the report as an artifact
      - name: 📝 Upload Scout Report
        id: upload-sarif
        if: github.event_name == 'push'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ env.SARIF_FILE }}

      # Update Docker Hub Repository Description
      - name: 📝 Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}
          short-description: "Demo application for GitHub Actions & Docker integration with multi-arch support"
          readme-filepath: ./README.md